<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <UseWindowsForms>true</UseWindowsForms>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Version>0.0.3</Version>
        <AssemblyOriginatorKeyFile>SimpleContextMenuKey.snk</AssemblyOriginatorKeyFile>
        <LangVersion>12</LangVersion>
        <TargetFramework>net481</TargetFramework>
        <SignAssembly>false</SignAssembly>
        <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <PlatformTarget>AnyCPU</PlatformTarget>
    </PropertyGroup>

    <ItemGroup Condition="'$(Configuration)' == 'Debug'">
        <ContentWithTargetPath Include="CopyToOutputDebug\**">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <TargetPath>%(RecursiveDir)\%(Filename)%(Extension)</TargetPath>
        </ContentWithTargetPath>
    </ItemGroup>

    <ItemGroup Condition="'$(Configuration)' == 'Release'">
        <ContentWithTargetPath Include="CopyToOutput\**">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <TargetPath>%(RecursiveDir)\%(Filename)%(Extension)</TargetPath>
        </ContentWithTargetPath>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Update="Properties\Resources.resx">
            <Generator>ResXFileCodeGenerator</Generator>
            <LastGenOutput>Resources.Designer.cs</LastGenOutput>
        </EmbeddedResource>
        <EmbeddedResource Remove="SharpShell\**"/>
        <EmbeddedResource Remove="ServerRegistrationManager\**"/>
        <EmbeddedResource Remove="ServerManager\**" />
    </ItemGroup>

    <ItemGroup>
        <Compile Update="Properties\Resources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Resources.resx</DependentUpon>
        </Compile>
        <Compile Remove="SharpShell\**"/>
        <Compile Remove="ServerRegistrationManager\**"/>
        <Compile Remove="ServerManager\**" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'net481'">
        <PackageReference Include="MimeTypeMapOfficial" Version="1.0.17"/>
    </ItemGroup>

    <ItemGroup>
        <None Remove="SharpShell\**"/>
        <None Remove="ServerRegistrationManager\**"/>
        <None Remove="ServerManager\**" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="SharpShell\SharpShell.csproj"/>
    </ItemGroup>

    <ItemGroup>
      <Reference Include="System.Resources.Extensions">
        <HintPath>Dependencies\System.Resources.Extensions.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
